dist: trusty
sudo: required
service:
  - docker

cache:
  apt: true

language: python
python:
  - "2.7"
  # - "pypy"

addons:
  apt:
    packages:
      - mysql-client-5.5
      - python-pip

install: .ci/install.sh
script: .ci/script.sh
after_success: .ci/after_success.sh
