version: '3'

services:
  iris-web:
    build: .
    ports:
      - "16649:16649"
    environment:
      - DOCKER_DB_BOOTSTRAP=1
      - IRIS_CFG_DB_HOST=iris-mysql
      - IRIS_CFG_DB_PASSWORD=1234
    depends_on:
      - iris-mysql
    volumes:
      - ./configs/config.dev.yaml:/home/iris/config/config.yaml

  iris-mysql:
    image: mysql:5.7
    command: mysqld --sql_mode="STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION"
    hostname: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=1234
