apiVersion: v1
kind: Service
metadata:
  name: iris
  labels:
    iris-component: api
    iris-component: web
    iris-version: {{ .Chart.AppVersion }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
spec:
  ports:
    - name: iris
      port: {{ .Values.irisService.externalPort }}
      targetPort: {{ .Values.irisService.internalPort }}
      protocol: TCP
  selector:
    app: {{ template "fullname" . }}
  type: NodePort
